# Generated by Django 4.2.30 on 2026-07-03 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_estimate_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandupUpdate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(verbose_name='Standup Date')),
                ('blockers', models.TextField(blank=True, default='', verbose_name='Blockers')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standup_updates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Standup Update',
                'verbose_name_plural': 'Standup Updates',
                'db_table': 'standup_updates',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='StandupTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('worked_yesterday', models.BooleanField(default=False)),
                ('working_today', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standup_tasks', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('standup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='db.standupupdate')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Standup Task',
                'verbose_name_plural': 'Standup Tasks',
                'db_table': 'standup_tasks',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='standupupdate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('member', 'project', 'date'), name='standup_unique_member_project_date_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='standupupdate',
            unique_together={('member', 'project', 'date', 'deleted_at')},
        ),
        migrations.AddConstraint(
            model_name='standuptask',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('standup', 'issue'), name='standup_task_unique_standup_issue_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='standuptask',
            unique_together={('standup', 'issue', 'deleted_at')},
        ),
    ]
